/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visualizacao;

import visualizacao.consultor.TelaConsultor;
import java.beans.PropertyVetoException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import modelo.Consultor;
import visualizacao.carro.TelaVeiculo;
import visualizacao.consultor.TelaNovaSenha;
import visualizacao.relatorios.AgendamentoTotal;
import visualizacao.relatorios.ConsultaAgendamentoDiario;

/**
 *
 * @author Rosaine Fiorio
 */
public class TelaPrincipal extends javax.swing.JFrame {

    public static Consultor consultor;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        this.lblNomeConsultor.setText(Inicializacao.CONSULTOR_LOGADO.getNome());
        new Relogio().start();
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/visualizacao/imagens/calendar.png")).getImage());
        
        menuRelatorios.setEnabled(Inicializacao.CONSULTOR_LOGADO.getGerente());
        miAgendamentoConsultor.setEnabled(Inicializacao.CONSULTOR_LOGADO.getGerente());
        miAgendamentoPeriodo.setEnabled(Inicializacao.CONSULTOR_LOGADO.getGerente());
        
        miConsultor.setEnabled(Inicializacao.CONSULTOR_LOGADO.getGerente());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telaInicio = new javax.swing.JDesktopPane();
        lblRelogio = new javax.swing.JLabel();
        statusPanel = new javax.swing.JPanel();
        lblConsultor = new javax.swing.JLabel();
        btnAlterarSenha = new javax.swing.JButton();
        lblNomeConsultor = new javax.swing.JLabel();
        menuPrincipal = new javax.swing.JMenuBar();
        menuCadastros = new javax.swing.JMenu();
        miCliente = new javax.swing.JMenuItem();
        miConsultor = new javax.swing.JMenuItem();
        miVeiculo = new javax.swing.JMenuItem();
        miAgedamento = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        miAgendamentoConsultor = new javax.swing.JMenuItem();
        miAgendamentoPeriodo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de agendamentos");
        setMinimumSize(new java.awt.Dimension(800, 600));

        lblRelogio.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblRelogio.setForeground(new java.awt.Color(255, 255, 255));
        lblRelogio.setText("08:00:00");
        lblRelogio.setBounds(10, 10, 730, 50);
        telaInicio.add(lblRelogio, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(telaInicio, java.awt.BorderLayout.CENTER);

        statusPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        statusPanel.setPreferredSize(new java.awt.Dimension(10, 49));

        lblConsultor.setText("Consultor:");

        btnAlterarSenha.setText("Alterar Senha");
        btnAlterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConsultor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNomeConsultor, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlterarSenha)
                .addContainerGap())
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAlterarSenha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNomeConsultor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblConsultor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(statusPanel, java.awt.BorderLayout.SOUTH);

        menuCadastros.setText("Cadastros");

        miCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        miCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visualizacao/imagens/cliente.png"))); // NOI18N
        miCliente.setText("Cliente");
        miCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miClienteActionPerformed(evt);
            }
        });
        menuCadastros.add(miCliente);

        miConsultor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        miConsultor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visualizacao/imagens/consultor.png"))); // NOI18N
        miConsultor.setText("Consultor");
        miConsultor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultorActionPerformed(evt);
            }
        });
        menuCadastros.add(miConsultor);

        miVeiculo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK));
        miVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visualizacao/imagens/carro.png"))); // NOI18N
        miVeiculo.setText("Veiculo");
        miVeiculo.setMinimumSize(new java.awt.Dimension(800, 600));
        miVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVeiculoActionPerformed(evt);
            }
        });
        menuCadastros.add(miVeiculo);

        miAgedamento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        miAgedamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visualizacao/imagens/agendamento.png"))); // NOI18N
        miAgedamento.setText("Agendamento");
        miAgedamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAgedamentoActionPerformed(evt);
            }
        });
        menuCadastros.add(miAgedamento);

        menuPrincipal.add(menuCadastros);

        menuRelatorios.setText("Relatórios");

        miAgendamentoConsultor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK));
        miAgendamentoConsultor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visualizacao/imagens/relatorio.png"))); // NOI18N
        miAgendamentoConsultor.setText("Agendamentos por Consultor");
        miAgendamentoConsultor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAgendamentoConsultorActionPerformed(evt);
            }
        });
        menuRelatorios.add(miAgendamentoConsultor);

        miAgendamentoPeriodo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        miAgendamentoPeriodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visualizacao/imagens/relatorio.png"))); // NOI18N
        miAgendamentoPeriodo.setText("Agendamentos Por Período");
        miAgendamentoPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAgendamentoPeriodoActionPerformed(evt);
            }
        });
        menuRelatorios.add(miAgendamentoPeriodo);

        menuPrincipal.add(menuRelatorios);

        setJMenuBar(menuPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miAgedamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAgedamentoActionPerformed
        TelaAgendamento telaAgenda = new TelaAgendamento();
        telaAgenda.setVisible(true);
        telaInicio.add(telaAgenda);
        try {
            telaAgenda.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_miAgedamentoActionPerformed

    private void miVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVeiculoActionPerformed
        TelaVeiculo telaVeiculo = new TelaVeiculo();
        telaVeiculo.setVisible(true);
        telaInicio.add(telaVeiculo);
        try {
            telaVeiculo.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_miVeiculoActionPerformed

    private void miConsultorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultorActionPerformed
        TelaConsultor telaConsultor = new TelaConsultor();
        telaConsultor.setVisible(true);
        telaInicio.add(telaConsultor);
        try {
            telaConsultor.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_miConsultorActionPerformed

    private void miClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miClienteActionPerformed
        TelaCliente tela = new TelaCliente();
        tela.setVisible(true);
        telaInicio.add(tela);
        try {
            tela.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        tela.toFront();
    }//GEN-LAST:event_miClienteActionPerformed

    private void miAgendamentoConsultorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAgendamentoConsultorActionPerformed
        ConsultaAgendamentoDiario tela = new ConsultaAgendamentoDiario();
        tela.setVisible(true);
        telaInicio.add(tela);
        try {
            tela.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        tela.toFront();

    }//GEN-LAST:event_miAgendamentoConsultorActionPerformed

    private void miAgendamentoPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAgendamentoPeriodoActionPerformed
        // TODO add your handling code here:
        AgendamentoTotal tela = new AgendamentoTotal();
        tela.setVisible(true);
        telaInicio.add(tela);
        try {
            tela.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        tela.toFront();
    }//GEN-LAST:event_miAgendamentoPeriodoActionPerformed

    private void btnAlterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarSenhaActionPerformed
        TelaNovaSenha telaNovaSenha = new TelaNovaSenha(Inicializacao.CONSULTOR_LOGADO);
        telaNovaSenha.setVisible(true);
        telaInicio.add(telaNovaSenha);
        try {
            telaNovaSenha.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        telaNovaSenha.toFront();
    }//GEN-LAST:event_btnAlterarSenhaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarSenha;
    private javax.swing.JLabel lblConsultor;
    private javax.swing.JLabel lblNomeConsultor;
    private javax.swing.JLabel lblRelogio;
    private javax.swing.JMenu menuCadastros;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenuItem miAgedamento;
    private javax.swing.JMenuItem miAgendamentoConsultor;
    private javax.swing.JMenuItem miAgendamentoPeriodo;
    private javax.swing.JMenuItem miCliente;
    private javax.swing.JMenuItem miConsultor;
    private javax.swing.JMenuItem miVeiculo;
    private javax.swing.JPanel statusPanel;
    private javax.swing.JDesktopPane telaInicio;
    // End of variables declaration//GEN-END:variables

    public JDesktopPane getTelaInicio() {
        return telaInicio;
    }

    public void setTelaInicio(JDesktopPane telaInicio) {
        this.telaInicio = telaInicio;
    }

    class Relogio extends Thread {

        @Override
        public void run() {
            lblRelogio.setText(new SimpleDateFormat("HH:mm:ss").format(new Date()));
            try {
                sleep(1000);
                run();
            } catch (InterruptedException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
}