/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visualizacao.consultor;

import javax.swing.JOptionPane;
import modelo.Consultor;
import modelo.dao.ConsultorDao;
import visualizacao.Inicializacao;
import visualizacao.componentes.messages.Messages;
import visualizacao.componentes.text.RequiredPasswordTextField;

/**
 *
 * @author Jhonnatan
 */
public class TelaNovaSenha extends javax.swing.JInternalFrame {

    private Consultor consultor;

    /**
     * Creates new form TelaNovaSenha
     */
    public TelaNovaSenha(Consultor consultor) {
        initComponents();
        this.consultor = consultor;

        this.lblUsuario.setText(this.consultor.getNome());
        this.txtSenhaAntiga.setEnabled(this.consultor == Inicializacao.CONSULTOR_LOGADO);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAtualizarSenha = new javax.swing.JButton();
        lblUsuario = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtSenhaAntiga = new visualizacao.componentes.text.RequiredPasswordTextField();
        txtNovaSenha = new visualizacao.componentes.text.RequiredPasswordTextField();
        txtConfirmacaoSenha = new visualizacao.componentes.text.RequiredPasswordTextField();

        setClosable(true);

        jLabel1.setText("Usuário");

        jLabel2.setText("Senha antiga");

        jLabel3.setText("Nova Senha");

        jLabel4.setText("Confirmação de senha");

        btnAtualizarSenha.setText("Atualizar senha");
        btnAtualizarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                            .addComponent(txtSenhaAntiga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNovaSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtConfirmacaoSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAtualizarSenha)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSenhaAntiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtConfirmacaoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAtualizarSenha)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atualizarSenha(){
        
    }
    
    private void btnAtualizarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarSenhaActionPerformed
        Boolean retorno = true;

        if (this.consultor == Inicializacao.CONSULTOR_LOGADO && !this.txtSenhaAntiga.runValidation()) {
            retorno = false;
        }

        if (!this.txtNovaSenha.runValidation()) {
            retorno = false;
        }

        if (!this.txtConfirmacaoSenha.runValidation()) {
            retorno = false;
        }

        if (!this.txtConfirmacaoSenha.getText().equals(this.txtNovaSenha.getText())) {
            this.txtConfirmacaoSenha.setText(null);
            this.txtConfirmacaoSenha.runValidation();
            this.txtNovaSenha.setText(null);
            this.txtNovaSenha.runValidation();
            this.txtNovaSenha.requestFocus();
            JOptionPane.showMessageDialog(this, "A nova senha e confirmação de senha são diferentes, por favor, redigite.");
            retorno = false;
        }

        if (!new ConsultorDao().verificarLogin(this.consultor, this.txtSenhaAntiga.getText())) {
            this.txtSenhaAntiga.setText(null);
            this.txtSenhaAntiga.runValidation();
            this.txtSenhaAntiga.requestFocus();
            JOptionPane.showMessageDialog(this, "Sua \"Senha atual\" está incorreta, por favor, redigite.");
            retorno = false;
        }

        if (retorno) {
            this.consultor.setSenha(this.txtNovaSenha.getText());
            if (this.consultor == Inicializacao.CONSULTOR_LOGADO) {
                Inicializacao.CONSULTOR_LOGADO = new ConsultorDao().salvar(this.consultor, true);
            } else {
                new ConsultorDao().salvar(this.consultor);
            }
            
            Messages.showInfoMessage("Senha atualizada com sucesso.");
            this.dispose();
        }
    }//GEN-LAST:event_btnAtualizarSenhaActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizarSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblUsuario;
    private visualizacao.componentes.text.RequiredPasswordTextField txtConfirmacaoSenha;
    private visualizacao.componentes.text.RequiredPasswordTextField txtNovaSenha;
    private visualizacao.componentes.text.RequiredPasswordTextField txtSenhaAntiga;
    // End of variables declaration//GEN-END:variables
}
