/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visualizacao.consultor;

import javax.swing.JFrame;
import modelo.Consultor;
import modelo.dao.ConsultorDao;
import visualizacao.Inicializacao;
import visualizacao.TelaPrincipal;
import visualizacao.componentes.messages.Messages;

/**
 *
 * @author Jhonnatan
 */
public class TelaTrocaSenha extends javax.swing.JFrame {

    /**
     * Creates new form TelaTrocaSenha
     */
    public TelaTrocaSenha() {
        initComponents();

        this.lblNomeConsultor.setText(Inicializacao.CONSULTOR_LOGADO.getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblNomeConsultor = new javax.swing.JLabel();
        btnAlterarSenha = new javax.swing.JButton();
        txtSenha = new visualizacao.componentes.text.RequiredPasswordTextField();
        txtConfirmacaoSenha = new visualizacao.componentes.text.RequiredPasswordTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Usuário:");

        jLabel2.setText("Senha");

        jLabel3.setText("Confirmação de senha");

        lblNomeConsultor.setText(" ");

        btnAlterarSenha.setText("Alterar senha");
        btnAlterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNomeConsultor, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                            .addComponent(txtSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtConfirmacaoSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAlterarSenha)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblNomeConsultor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtConfirmacaoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlterarSenha)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarSenhaActionPerformed
        Boolean retorno = true;
        if (!this.txtSenha.runValidation() || !this.txtConfirmacaoSenha.runValidation()) {
            retorno = false;
        }else if(!(this.txtSenha.getText().equals(this.txtConfirmacaoSenha.getText()))){
            retorno = false;
            Messages.showWarningMessage("Sua senha e confirmação de senha são diferentes, por favor, redigite.");
            this.txtSenha.setText(null);
            this.txtSenha.runValidation();
            this.txtSenha.requestFocus();
            this.txtConfirmacaoSenha.setText(null);
            this.txtConfirmacaoSenha.runValidation();
        }

        if (retorno) {
            Inicializacao.CONSULTOR_LOGADO.setSenha(this.txtSenha.getText());
            Inicializacao.CONSULTOR_LOGADO.setTrocarSenha(false);

            Inicializacao.CONSULTOR_LOGADO = new ConsultorDao().salvar(Inicializacao.CONSULTOR_LOGADO);

            if (Inicializacao.CONSULTOR_LOGADO instanceof Consultor) {
                TelaPrincipal telaPrincipal = new TelaPrincipal();
                telaPrincipal.setExtendedState(JFrame.MAXIMIZED_BOTH);
                telaPrincipal.setVisible(true);
                telaPrincipal.setResizable(false);

                Inicializacao.AREA_DE_TRABALHO = telaPrincipal.getTelaInicio();
            } else {
                Messages.showErrorMessage("Ocorreu um erro ao atualizar sua senha, por favor, reinicie o processo.");
            }
            this.dispose();
        }
    }//GEN-LAST:event_btnAlterarSenhaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblNomeConsultor;
    private visualizacao.componentes.text.RequiredPasswordTextField txtConfirmacaoSenha;
    private visualizacao.componentes.text.RequiredPasswordTextField txtSenha;
    // End of variables declaration//GEN-END:variables
}
