/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visualizacao.relatorios;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Agendamento;
import modelo.Consultor;
import modelo.dao.AgendamentoDao;
import visualizacao.componentes.text.formatted.DataTextField;

/**
 *
 * @author Jhonnatan
 */
public class AgendamentoTotal extends javax.swing.JInternalFrame {

    /**
     * Creates new form AgendamentoTotal
     */
    
    private List<Agendamento> agendamentos;
   
    
    public AgendamentoTotal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtlDataInicial = new DataTextField(true);
        txtDataFinal = new DataTextField(true);
        btnBuscarAgendamentos = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblAgendadosValor = new javax.swing.JLabel();
        lblRetornosValor = new javax.swing.JLabel();
        lblInspecoesValor = new javax.swing.JLabel();
        lblOrcamentosValor = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblPrazoCumpridoValor = new javax.swing.JLabel();
        lblExplicacaoServicoValor = new javax.swing.JLabel();
        lblRequisicaoPecasValor = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lblServicosValor = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        lblEntradasValor = new javax.swing.JLabel();
        jbGerarRelatorio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/visualizacao/imagens/relatorio.png"))); // NOI18N

        btnBuscarAgendamentos.setText("Buscar");
        btnBuscarAgendamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAgendamentosActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados gerais"));

        jLabel10.setText("Agendados");

        jLabel11.setText("Retornos");

        jLabel12.setText("Inspeções");

        jLabel13.setText("Orçamentos");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel18.setText("Prazo cumprido");

        jLabel19.setText("Explicação do serviço");

        jLabel20.setText("Requisições de peças");

        jLabel24.setText("Serviços");

        jLabel26.setText("Entradas");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAgendadosValor, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(lblRetornosValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblInspecoesValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblOrcamentosValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblServicosValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEntradasValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrazoCumpridoValor, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(lblExplicacaoServicoValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRequisicaoPecasValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(lblPrazoCumpridoValor))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(lblExplicacaoServicoValor))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(lblRequisicaoPecasValor)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel24)
                                    .addComponent(lblServicosValor))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel26)
                                    .addComponent(lblEntradasValor))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(lblAgendadosValor))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(lblRetornosValor))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(lblInspecoesValor))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(lblOrcamentosValor))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jbGerarRelatorio.setText("Gerar Relatório");
        jbGerarRelatorio.setEnabled(false);
        jbGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGerarRelatorioActionPerformed(evt);
            }
        });

        jLabel1.setText("Data Inicial");

        jLabel4.setText("Data Final");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtlDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscarAgendamentos))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbGerarRelatorio, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtlDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarAgendamentos)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbGerarRelatorio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarAgendamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAgendamentosActionPerformed
        try {
            this.agendamentos = new AgendamentoDao().contaAgendamentosConsultores(new SimpleDateFormat("dd/MM/yyyy HH:mm:ss").parse(txtlDataInicial.getText()+" 00:00:00"), new SimpleDateFormat("dd/MM/yyyy HH:mm:ss").parse(txtDataFinal.getText()+" 23:59:59"));
            Integer servicos = 0;
            Integer agendados = 0;
            Integer entradas = 0;
            Integer explicacao = 0;
            Integer inspecoes = 0;
            Integer orcamentos = 0;
            Integer prazo = 0;
            Integer requisicao = 0;
            Integer retorno = 0;

            for (Agendamento agendamento : agendamentos) {
                if (!agendamento.getRetorno()) {
                    servicos++;
                }

                if (agendamento.getAgendado()) {
                    agendados++;
                }

                if (agendamento.getExplicacaoTrabalho()) {
                    explicacao++;
                }
                if (agendamento.getElevador()) {
                    inspecoes++;
                }
                if (agendamento.getOrcamento()) {
                    orcamentos++;
                }
                if (agendamento.getVeiculoProntoRevisado()) {
                    prazo++;
                }
                if (agendamento.getRequisicaoPecas()) {
                    requisicao++;
                }
                if (agendamento.getRetorno()) {
                    retorno++;
                }
                if (agendamento.getEfetivo()) {
                    entradas++;
                }
            }

            lblServicosValor.setText(servicos.toString());
            lblAgendadosValor.setText(agendados.toString());
            lblEntradasValor.setText(entradas.toString());
            lblExplicacaoServicoValor.setText(explicacao.toString());
            lblInspecoesValor.setText(inspecoes.toString());
            lblOrcamentosValor.setText(orcamentos.toString());
            lblPrazoCumpridoValor.setText(prazo.toString());
            lblRequisicaoPecasValor.setText(requisicao.toString());
            lblRetornosValor.setText(retorno.toString());
            jbGerarRelatorio.setEnabled(true);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Data inválida.");
        }
    }//GEN-LAST:event_btnBuscarAgendamentosActionPerformed

    private void jbGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGerarRelatorioActionPerformed
        try {
            try {
                // TODO add your handling code here:
                relatorioContaAgendamentoTotal();
            } catch (ParseException ex) {
                Logger.getLogger(AgendamentoTotal.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ConsultaAgendamentoDiario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(ConsultaAgendamentoDiario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ConsultaAgendamentoDiario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbGerarRelatorioActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarAgendamentos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbGerarRelatorio;
    private javax.swing.JLabel lblAgendadosValor;
    private javax.swing.JLabel lblEntradasValor;
    private javax.swing.JLabel lblExplicacaoServicoValor;
    private javax.swing.JLabel lblInspecoesValor;
    private javax.swing.JLabel lblOrcamentosValor;
    private javax.swing.JLabel lblPrazoCumpridoValor;
    private javax.swing.JLabel lblRequisicaoPecasValor;
    private javax.swing.JLabel lblRetornosValor;
    private javax.swing.JLabel lblServicosValor;
    private javax.swing.JTextField txtDataFinal;
    private javax.swing.JTextField txtlDataInicial;
    // End of variables declaration//GEN-END:variables
public void relatorioContaAgendamentoTotal() throws FileNotFoundException, DocumentException, IOException, ParseException {

        String fileName = System.getProperty("user.dir")+"\\relatorio-geral-"+new SimpleDateFormat("dd-mm-yyyy").format(new Date())+".pdf";

        Font font = new Font(Font.FontFamily.TIMES_ROMAN, 10);

        Document document = new Document();

        FileOutputStream fileOutputStream = new FileOutputStream(fileName);

        PdfWriter.getInstance(document, fileOutputStream);

        document.open();

        Paragraph title = new Paragraph("Agendamentos  - Estatisticas Totais Por Período", font);
        title.setSpacingAfter(2);
        title.setAlignment(Element.ALIGN_CENTER);

        document.add(title);
        
        Paragraph periodo = new Paragraph("De: " + txtlDataInicial.getText() + " Até: " +  txtDataFinal.getText(), font);
        periodo.setSpacingAfter(2);
        periodo.setSpacingBefore(2);
        periodo.setAlignment(Element.ALIGN_LEFT);

        document.add(periodo);
               
        
        PdfPTable pdfPTable = new PdfPTable(9);
        pdfPTable.setWidthPercentage(100);

        pdfPTable.addCell(new PdfPCell(new Phrase("Serviços", font)));
        pdfPTable.addCell(new PdfPCell(new Phrase("Entradas", font)));
        pdfPTable.addCell(new PdfPCell(new Phrase("Agendados", font)));
        pdfPTable.addCell(new PdfPCell(new Phrase("Retornos", font)));
        pdfPTable.addCell(new PdfPCell(new Phrase("Inspeçoes", font)));
        pdfPTable.addCell(new PdfPCell(new Phrase("Orçamentos", font)));
        pdfPTable.addCell(new PdfPCell(new Phrase("Prazos Cumpridos", font)));
        pdfPTable.addCell(new PdfPCell(new Phrase("Explicação dos Serviços", font)));
        pdfPTable.addCell(new PdfPCell(new Phrase("Requisição de Peças", font)));

        
        pdfPTable.addCell(new PdfPCell(new Phrase(lblServicosValor.getText(), font)));
        pdfPTable.addCell(new PdfPCell(new Phrase(lblEntradasValor.getText(), font)));
        pdfPTable.addCell(new PdfPCell(new Phrase(lblAgendadosValor.getText(), font)));
        pdfPTable.addCell(new PdfPCell(new Phrase(lblRetornosValor.getText(), font)));
        pdfPTable.addCell(new PdfPCell(new Phrase(lblInspecoesValor.getText(), font)));
        pdfPTable.addCell(new PdfPCell(new Phrase(lblOrcamentosValor.getText(), font)));
        pdfPTable.addCell(new PdfPCell(new Phrase(lblPrazoCumpridoValor.getText(), font)));
        pdfPTable.addCell(new PdfPCell(new Phrase(lblExplicacaoServicoValor.getText(), font)));
        pdfPTable.addCell(new PdfPCell(new Phrase(lblRequisicaoPecasValor.getText(), font)));
        

        document.add(pdfPTable);

        document.close();

        Desktop.getDesktop().open(new File(fileName));
    }

}
